title = "Sandboxer"

gitSourceBranch = "main"
changelog = true
classOrder = [
    "Sandboxer",
    "InstanceSandboxer",
    "InstanceList",
]

[docusaurus]
url = "https://littlebitsman.dev"
baseUrl = "/sandboxer"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

[footer]
style = "dark"
copyright = "Copyright © 2025 littleBitsman. Docs built with Moonwave and Docusaurus"
