gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"
favicon = ""

[footer]
style = "dark"
copyright = "Copyright © 2025 littleBitsman. Docs built with Moonwave and Docusaurus"
